# Visualizations Notebook

The following notebook has as a purpose to show visualizations regarding the Education status at South America.

### Set up of libraries

In [38]:
import pandas as pd
import altair as alt
import requests

In [2]:
from utils import filters_countries_cols

In [50]:
# Loading the data
data = pd.read_csv("../data/cleaned/cleaned_data.csv")
all_countries = data[data["country_code"].notna()]
avg_outcome = pd.read_csv("../data/cleaned/avg_outcome.csv")

In [51]:
all_countries

,Unnamed: 0,country,country_code,year,net_enrollment,gov_exp_pct_gdp,lit_rate_adult_pct,pri_comp_rate_pct,pupil_teacher_primary,pupil_teacher_secondary,...,"Current education expenditure, secondary (% of total expenditure in secondary public institutions)","Current education expenditure, tertiary (% of total expenditure in tertiary public institutions)",Demand for family planning satisfied by modern methods (% of married women with demand for family planning),"Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)","Government expenditure on education, total (% of government expenditure)",People using at least basic drinking water services (% of population),Teenage mothers (% of women ages 15-19 who have had children or are currently pregnant),Trained teachers in lower secondary education (% of total teachers),"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)"
0,26,Afghanistan,AFG,1950,3.50000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27,Afghanistan,AFG,1955,4.67000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28,Afghanistan,AFG,1960,7.27000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29,Afghanistan,AFG,1965,12.92000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30,Afghanistan,AFG,1970,16.96000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6037,9079,Zimbabwe,ZWE,2019,81.61865,NaN,93.227547,90.232155,NaN,NaN,...,NaN,NaN,NaN,NaN,75.001228,10.463589,63.094954,NaN,NaN,NaN
6038,9080,Zimbabwe,ZWE,2020,83.08571,NaN,NaN,91.866905,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,15.666611,62.666456,NaN,NaN,NaN
6039,9081,Zimbabwe,ZWE,2021,90.57390,NaN,NaN,86.099625,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,62.252798,NaN,NaN,NaN
6040,9082,Zimbabwe,ZWE,2022,91.82661,NaN,89.849998,86.116936,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,62.294255,NaN,NaN,NaN
6041,9083,Zimbabwe,ZWE,2023,90.86277,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.688962,NaN,NaN,NaN,NaN

In [52]:
avg_outcome

,Unnamed: 0,country,country_code,year,test_scores,gdp_pc,population,wb_region
0,0,Afghanistan,AFG,2017,355.0000,2952.9990,35688941.0,NaN
1,1,Afghanistan,AFG,2018,354.7588,2902.3920,36743040.0,NaN
2,2,Afghanistan,AFG,2020,354.7588,2769.6858,39068977.0,NaN
3,3,Afghanistan,AFG,2000,NaN,1617.8264,20130334.0,NaN
4,4,Afghanistan,AFG,2001,NaN,1454.1108,20284303.0,NaN
...,...,...,...,...,...,...,...,...
59286,59286,Zimbabwe,ZWE,1985,NaN,NaN,8686815.0,NaN
59287,59287,Zimbabwe,ZWE,1986,NaN,NaN,8982579.0,NaN
59288,59288,Zimbabwe,ZWE,1987,NaN,NaN,9284649.0,NaN
59289,59289,Zimbabwe,ZWE,1988,NaN,NaN,9583099.0,NaN
59290,59290,Zimbabwe,ZWE,1989,NaN,NaN,9864797.0,NaN

### Set up for South American Countries

In [5]:
sa_countries = ["Argentina", "Chile", "Peru", "Colombia", "Bolivia",
                "Eduador", "Venezuela", "Paraguay", "Uruguay", "Brazil"]

# **First Chart: Evolution primary net enrollment since 1950 for South American countries**

This dataset includes the historical evolution of enrollment of primary education
by South American country since 1950

(net enrollment: of kids of age of going to primary school, how many of them are going)

In [10]:
# Getting the data
cols_1 = ["country", "year", "net_enrollment"]
enrollment_sa = filters_countries_cols(all_countries, cols)

enroll_time = alt.Chart(enrollment_sa).mark_line().encode(
    x="year",
    y="net_enrollment",
    color = "country",    
)

# **Second Chart: Scatter Plot relating GDP per capita in 2020 with test_scores

GDP per capita data is expressed in international-$ at 2021 prices.

The Harmonized Learning Outcomes (HLO) database: used by organizations like the World Bank, compiles scores from tests such as TIMSS, PISA, and others to create a single, comparable score for learning outcomes.

In [ ]:
df_3 = avg_outcome[avg_outcome["year"] == 2020]
df_3 = df_3[df_3["gdp_pc"] <= 120000]

chart_2 = alt.Chart(df_3).mark_circle().encode(
    x = alt.X("gdp_pc", scale = alt.Scale(domain = [0, 120000])),
    y = alt.Y("test_scores"))

alt.Chart(...)

# **Third Chart**: Relation of pupil-teacher primary

In [70]:
all_countries

,Unnamed: 0,country,country_code,year,net_enrollment,gov_exp_pct_gdp,lit_rate_adult_pct,pri_comp_rate_pct,pupil_teacher_primary,pupil_teacher_secondary,...,"Current education expenditure, secondary (% of total expenditure in secondary public institutions)","Current education expenditure, tertiary (% of total expenditure in tertiary public institutions)",Demand for family planning satisfied by modern methods (% of married women with demand for family planning),"Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)","Government expenditure on education, total (% of government expenditure)",People using at least basic drinking water services (% of population),Teenage mothers (% of women ages 15-19 who have had children or are currently pregnant),Trained teachers in lower secondary education (% of total teachers),"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)"
0,26,Afghanistan,AFG,1950,3.50000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27,Afghanistan,AFG,1955,4.67000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28,Afghanistan,AFG,1960,7.27000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29,Afghanistan,AFG,1965,12.92000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30,Afghanistan,AFG,1970,16.96000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6037,9079,Zimbabwe,ZWE,2019,81.61865,NaN,93.227547,90.232155,NaN,NaN,...,NaN,NaN,NaN,NaN,75.001228,10.463589,63.094954,NaN,NaN,NaN
6038,9080,Zimbabwe,ZWE,2020,83.08571,NaN,NaN,91.866905,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,15.666611,62.666456,NaN,NaN,NaN
6039,9081,Zimbabwe,ZWE,2021,90.57390,NaN,NaN,86.099625,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,62.252798,NaN,NaN,NaN
6040,9082,Zimbabwe,ZWE,2022,91.82661,NaN,89.849998,86.116936,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,62.294255,NaN,NaN,NaN
6041,9083,Zimbabwe,ZWE,2023,90.86277,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.688962,NaN,NaN,NaN,NaN